### ISSUE TITLE
The mark all as read button opens up the subscribed list 

### ISSUE THREAD

**Issue by SDee001** [spacecowboy/Feeder#425] opened 2024-11-18 14:28 UTC
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.7

### Where did you get the app from

Other

### Android version

no

### Device model

samsung f12

### First occurred

after update or one day ago

### Steps to reproduce

1. Open app
2. Tap mark all as read button
3. It opens the subscription list

### Expected behaviour

It should juat mark all as read and make the screen nothing to read appar

### Current behaviour

Opens up the subscription list

**Comment by spacecowboy** [comment] 2024-11-18 16:17
Not a bug.

 @maksimowiczm implemented this change.

**Comment by spacecowboy** [comment] 2024-11-18 16:18
See previous feature request: https://github.com/spacecowboy/Feeder/issues/375

**Comment by joavd** [comment] 2024-11-18 18:45
Facing the same here. After reading through the linked ticket I'm still kinda lost.

What exactly do you need to do to mark things as Read (and remove them from the list) after hitting the "Mark all as read" button?

For me it opens up the drawer but then there's only an option to switch tabs, nothing else.

**Comment by wiredOr** [comment] 2024-11-19 06:46
Issue happens for me as well on pixel 8 pro, Android 15.

**Comment by trlef19** [comment] 2024-11-19 10:31
It's indeed a feature. I don't like it though. It's confusing. Maybe add a toggle for it? I don't get the point either :(

**Comment by joavd** [comment] 2024-11-19 10:35
How come it's a feature though? It's not marking stuff as Read, it only opens the drawer.

Or is it a bug only for some?

**Comment by trlef19** [comment] 2024-11-19 12:08
It does both for me

**Comment by joavd** [comment] 2024-11-19 13:04
@spacecowboy makes sense  thanks!

But the default behaviour changed, before the update it was marking as read + hiding. Now it doesn't.

Did the settings change or were reset?

**Comment by trlef19** [comment] 2024-11-19 17:03
personally, since i dont have a lot have a lot of feeds, i read them from "all" and then i hit read. So opening the drawer doesnt work for me :((

**Comment by blair-n** [comment] 2024-11-19 18:47
I'm having this issue too since yesterday. Clicking "Mark all as read" previously used to also clear all the read conversations. Now it just opens the side drawer.

**Comment by maksimowiczm** [comment] 2024-11-19 19:29
I think the issue here is that something went wrong with migrating filter settings in [this commit](https://github.com/spacecowboy/Feeder/commit/de1c7dd29edbaa790ed56649915c38d3555fac91). To fix that, you just need to change the feed filter (disable Read).

**Comment by spacecowboy** [comment] 2024-11-19 19:57
> @spacecowboy makes sense thanks!
> 
> But the default behaviour changed, before the update it was marking as read + hiding. Now it doesn't.
> 
> Did the settings change or were reset?

Yes the default setting changed. You never toggled it, so that's why it changed for you.

TBH I did not expect any current user to get their setting changed, so I apologize for that.

**Comment by blair-n** [comment] 2024-11-19 20:04
> I think the issue here is that something went wrong with migrating filter settings in [this commit](https://github.com/spacecowboy/Feeder/commit/de1c7dd29edbaa790ed56649915c38d3555fac91). To fix that, you just need to change the feed filter (disable Read).

That helps. Thanks so much!

**Comment by Brottweiler** [comment] 2024-11-20 14:42
I find this feature highly annoying because I am almost always in the all feeds tab and I do not hide entries that I have read.
Maybe it's nice to open the drawer when you have selected a specific feed but it still feels like a setting to change this behaviour would be nice.

**Comment by RMHogervorst** [comment] 2024-11-22 05:29
> If you un-toggle showing read items it

I don't see this option in settings though

**Comment by jeffreyd00** [comment] 2024-11-23 21:46
> > How come it's a feature though? It's not marking stuff as Read, it only opens the drawer.
> > Or is it a bug only for some?
> 
> It IS marking them as read but you don't notice it.
> 
> If you un-toggle showing read items it will become very clear to you.
> 
> I think there is a clear difference here depending on how you use Feeder.
> 
> If you usually hide read items, then hitting the FAB will remove everything from the screen so it makes sense that you'd want to open a different feed/tag after that.
> 
> If you show read times, maybe you still want to scroll and read something else though. And in that scenario, opening the navigation drawer might seem weird.
> 
> Personally I always hide read items.

I have no such option in Settings. Regardless, it seems this is not the feature people are wanting

**Comment by blair-n** [comment] 2024-11-23 22:38
> > > How come it's a feature though? It's not marking stuff as Read, it only opens the drawer.
> > > Or is it a bug only for some?
> > 
> > 
> > It IS marking them as read but you don't notice it.
> > If you un-toggle showing read items it will become very clear to you.
> > I think there is a clear difference here depending on how you use Feeder.
> > If you usually hide read items, then hitting the FAB will remove everything from the screen so it makes sense that you'd want to open a different feed/tag after that.
> > If you show read times, maybe you still want to scroll and read something else though. And in that scenario, opening the navigation drawer might seem weird.
> > Personally I always hide read items.
> 
> I have no such option in Settings. Regardless, it seems this is not the feature people are wanting

The filter is not in settings. It's the filter icon in the top right of the feed.

**Comment by jeffreyd00** [comment] 2024-11-23 22:46
Got it though its not intuitive  Filter | Recently Read (toggle off).
That being said, thank you very much for your programming skills. I've
supported the efforts in the past.

**Comment by dougVanny** [comment] 2024-11-25 23:27
As an user, I strongly wish I could disable this behavior. The implemented feature assumes a specific behavior from the user, which does not apply to everyone as seen by the comments above.

The intention behind the proposal, guiding the user to read articles from other feeds after they're done with their current one, has merit, but I wouldn't do so by pulling the user from one screen context to another. I would consider for example a double tap for it to happen, not unlike tapping the mark as read button and then the open another feed link

**Comment by pstorch** [comment] 2024-11-26 06:08
A understanding and respect the initial feature requests, but I'm also in the team "don't do it on the All feeds tab"

**Comment by spacecowboy** [comment] 2024-11-26 12:03
> As an user, I strongly wish I could disable this behavior. The implemented feature assumes a specific behavior from the user, which does not apply to everyone as seen by the comments above.
> 
> The intention behind the proposal, guiding the user to read articles from other feeds after they're done with their current one, has merit, but I wouldn't do so by pulling the user from one screen context to another. I would consider for example a double tap for it to happen, not unlike tapping the mark as read button and then the open another feed link

double tap is not a thing in touch interfaces

**Comment by spacecowboy** [comment] 2024-11-26 12:04
I think the minimum thing we can all agree on is that if you are viewing All feeds, then marking All as read should not open the nav drawer.

**Comment by smith6k** [comment] 2024-11-27 06:12
There would be no need to argue it this just was a setting:
Open drawer on fab click  [yes/no].

Can this be done?

Thanks

**Comment by spacecowboy** [comment] 2024-11-27 09:00
> There would be no need to argue if this just was a setting: Open drawer on fab click [yes/no].
> 
> Can this be done?
> 
> Thanks

It *CAN* be done. But all settings add complexity so they are added very restrictively. In this case it's probably warranted

**Comment by SDee001** [comment] 2024-11-28 03:06
> I think the minimum thing we can all agree on is that if you are viewing All feeds, then marking All as read should not open the nav drawer.

Yeah!

**Comment by rexxfan** [comment] 2024-11-28 21:59
> > I think the minimum thing we can all agree on is that if you are viewing All feeds, then marking All as read should not open the nav drawer.
> 
> Yeah!

I strongly second this. Don't open the drawer if the user is viewing AllFeeds. But opening it automatically at all seems fairly heavy handed. Is it that difficult for someone who wants to look at more feeds to just open it themselves? Or is the main concern users who may not be aware that they have subscribed to other feeds? I'm not convinced that is even a thing.

**Comment by spacecowboy** [comment] 2024-12-03 21:01
Setting added in https://github.com/spacecowboy/Feeder/pull/440

**Closed** 2024-12-03 21:20 UTC
Labels: Type: Question / support
