### ISSUE TITLE
search engine

### ISSUE THREAD

**Issue by foxmask** [spacecowboy/Feeder#439] opened 2024-11-30 21:01 UTC
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.7.0

### Where did you get the app from

F-Droid

### Feature or improvement you want

hello
could we have a search engine to be able to look for a (read/unread)  post ?

### Why should this be added?

often I feel frustrated to not be able to retrieve a post I read some days ago and can’t remember a title but remember some text.

thanks

**Comment by MrBrowner** [comment] 2024-12-03 02:27
+1

**Comment by spacecowboy** [comment] 2024-12-03 18:30
Duplicate of https://github.com/spacecowboy/Feeder/issues/368

**Closed by spacecowboy** 2024-12-03 18:30 UTC
Labels: Type: Feature request, Needs: Triage
